resources:
- icon: git
  name: experiment-repo
  source:
    branch: master
    uri: https://github.com/vvijay777/concourse.git
  type: git


jobs:
  - name: job
    plan:
      - get: experiment-repo
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args:
              - "-c"
              - |     
                df -k
                cd /experiment-repo
                ls -lrth
                asg=$(cat properties.cfg | grep asg | cut -d'=' -f2)
