resources:
- icon: git
  name: experiment-repo
  source:
    branch: master
    uri: https://github.com/vvijay777/concourse.git
  type: git


jobs:
  - name: job
    plan:
      - get: experiment-repo
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
          - name: experiment-repo
          run:
            path: sh
            args:
              - "-c"
              - |     
                cd experiment-repo
                alb=$(cat properties.cfg | grep asg | cut -d'=' -f2)
                asg=$(cat properties.cfg | grep asg | cut -d'=' -f2)
                echo $asg
                echo $alb
                more asg.json
                sed -i "/^[[:space:]]*\"url\"/ s/:.*/:\ \"\http:\/\/$alb\"/" asg.json
                sed -i "/^[[:space:]]*\"asg_names\"/ s/:.*/:\ [\"$asg\"],/" asg.json
                more asg.json
