resources:
- icon: git
  name: experiment-repo
  source:
    branch: master
    uri: https://github.com/vvijay777/concourse.git
  type: git


jobs:
  - name: job
    plan:
      - get: experiment-repo
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
          - name: experiment-repo
          run:
            path: sh
            args:
              - "-c"
              - |     
                cd experiment-repo
                echo "Running the Script to take the User Input mentioned in the Properties.cfg File"
                sh user_input.sh
                echo "Running the Chaos Experiment after changing the values based on Property File"
                chaos run asg.json
